server:
 port: 8080
 
urls:
 rsybl: http://192.1.1.15:8280/rSYBL/ #192.1.1.15
 store: http://datastore-research-governify.herokuapp.com/api/v5/
 mela: http://192.1.1.15:8180/MELA-AnalysisService/
 
timers:
 availability: 1 #time in minutes
 throughput: 30 #time in seconds
 store: 2 #time in seconds
 rsybl: 180 #time in seconds
 routing: 2 #time in seconds
 
governanceProperties: 

 levels:
  - l00
  - l01
  
 service:
  id: Governed
  unitTh: 6
  scalable: false
  
 levelElasticityPercentages:
  pro: 0.5
  basic: 0
 
 levelMinInstances:
  pro: 2
  basic: 1
  
 defaultRules:
  basic: DN_ST2:STRATEGY CASE throughput > 140*numberOfVMs #:scaleOut;DN_ST2:STRATEGY CASE throughput <= 140*numberOfVMs-1 #:scaleIn
  pro: DN_ST2:STRATEGY CASE throughput > 140*numberOfVMs #:scaleOut;DN_ST2:STRATEGY CASE throughput <= 140*numberOfVMs-1 #:scaleIn
  
 routerConfig:
  basic:
    nextLevel: 0.7
    backLevel: 0.8
  pro:
    nextLevel: 0.7
    backLevel: 0.8
 